generateOres = true
blacklistedOres = ["bauxite", "lead", "tin", "tungsten"]
spawnWithGuideBook = true
respawnWithGuideBook = true
disableFuelTooltips = false
disableItemTagTooltips = false
newVersionMessage = true
enableHatchPlacementOverlay = true
colorWaterLava = true
enableDebugCommands = false
